=== brekka/stillingar/core/src/test/xsd/TestConfiguration-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://brekka.org/xml/stillingar/test/v1"
    xmlns:log4j="http://jakarta.apache.org/log4j/" xmlns:st="http://brekka.org/xml/stillingar/test/v1"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xsd:element name="Configuration">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="MOTD" maxOccurs="1" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ID" type="st:UUIDType" maxOccurs="1" minOccurs="0"></xsd:element>
                            <xsd:element name="Message" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
                            <xsd:element name="Expires" type="xsd:dateTime" maxOccurs="1" minOccurs="0"></xsd:element>
                            <xsd:element name="Language" type="xsd:language" maxOccurs="1" minOccurs="0"></xsd:element>
                            <xsd:element name="References" type="st:UUIDType" maxOccurs="unbounded" minOccurs="0"></xsd:element>
                        </xsd:sequence>
                        <xsd:attribute type="xsd:token" name="id" />
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="FeatureFlag" maxOccurs="unbounded" minOccurs="0">
                    <xsd:complexType>
                        <xsd:simpleContent>
                            <xsd:extension base="xsd:boolean">
                                <xsd:attribute name="key" type="xsd:string" use="required" />
                            </xsd:extension>
                        </xsd:simpleContent>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Database" type="st:DatabaseType" maxOccurs="1" minOccurs="0"></xsd:element>
                <xsd:element name="CompanyX" maxOccurs="1" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="SalesWebService" type="st:WebServiceType"></xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="CompanyY" maxOccurs="1" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="WarehouseWebService" type="st:WebServiceType"></xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Services" maxOccurs="1" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Rules">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Transaction">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="MaxQuantity" type="xsd:int"></xsd:element>
                                                    <xsd:element name="MaxAmount" type="xsd:decimal"></xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="Fraud">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="Enabled" type="xsd:boolean"></xsd:element>
                                                    <xsd:element name="TriggerFactor" type="xsd:float"></xsd:element>
                                                    <xsd:element name="Scale" type="xsd:short"></xsd:element>
                                                    <xsd:element name="Length" type="xsd:long"></xsd:element>
                                                    <xsd:element name="Keyword" type="xsd:string" maxOccurs="unbounded"
                                                        minOccurs="0"></xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Security" maxOccurs="1" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="PublicKey" type="xsd:base64Binary"></xsd:element>
                            <xsd:element name="Factor" type="xsd:integer"></xsd:element>
                            <xsd:element name="Flag" type="xsd:byte"></xsd:element>
                            <xsd:element name="TimeUnit" minOccurs="0">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="DAYS" />
                                        <xsd:enumeration value="HOURS" />
                                        <xsd:enumeration value="MINUTES" />
                                        <xsd:enumeration value="SECONDS" />
                                        <xsd:enumeration value="MILLISECONDS" />
                                        <xsd:enumeration value="MICROSECONDS" />
                                        <xsd:enumeration value="NANOSECONDS" />
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="LockDuration" type="xsd:duration" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Logging" maxOccurs="1" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:any processContents="skip" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="ApplicationContext" maxOccurs="1" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:any processContents="skip" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="WebServiceType">
        <xsd:sequence>
            <xsd:element name="URL" type="xsd:anyURI" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="Username" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
            <xsd:element name="Password" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
            <xsd:element name="Proxy" type="st:HttpProxyType" maxOccurs="1" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="HttpProxyType">
        <xsd:sequence>
            <xsd:element name="URL" type="xsd:anyURI" maxOccurs="1" minOccurs="1"></xsd:element>
            <xsd:element name="Username" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
            <xsd:element name="Password" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="DatabaseType">
        <xsd:choice>
            <xsd:sequence>
                <xsd:element name="DataSource" type="xsd:string" maxOccurs="1" minOccurs="1" />
            </xsd:sequence>
            <xsd:sequence>
                <xsd:element name="URL" type="xsd:anyURI" maxOccurs="1" minOccurs="1"></xsd:element>
                <xsd:element name="Driver" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
                <xsd:element name="Username" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
                <xsd:element name="Password" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
            </xsd:sequence>
        </xsd:choice>
    </xsd:complexType>

    <xsd:simpleType name="UUIDType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}" />
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== brekka/stillingar/xmlbeans/src/test/resources/org/brekka/stillingar/xmlbeans/TestConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration xmlns="http://brekka.org/xml/stillingar/test/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://brekka.org/xml/stillingar/test/v1 http://brekka.org/schema/stillingar/test/TestConfiguration-1.0.xsd">
    <!-- Test Comment -->
    <MOTD id="1">
        <ID>64829ee9-d265-47bb-8fb4-4ab4ada0cdfc</ID>
        <Message>Test message</Message>
        <Expires>2012-12-31T12:00:00</Expires>
    </MOTD>
    <FeatureFlag key="TURBO">true</FeatureFlag>
    <FeatureFlag key="DEBUG">false</FeatureFlag>
    <Database>
        <DataSource>jdbc/test</DataSource>
    </Database>
    <CompanyY>
        <WarehouseWebService>
            <URL>http://example.org/CompanyY</URL>
            <Username>Username</Username>
            <Password>Password</Password>
        </WarehouseWebService>
    </CompanyY>
    <Services>
        <Rules>
            <Transaction>
                <MaxQuantity>42</MaxQuantity>
                <MaxAmount>50000.73</MaxAmount>
            </Transaction>
            <Fraud>
                <Enabled>true</Enabled>
                <TriggerFactor>0.89</TriggerFactor>
                <Scale>169</Scale>
                <Length>85697458963323</Length>
                <Keyword>KeywordA</Keyword>
                <Keyword>KeywordB</Keyword>
                <Keyword>KeywordC</Keyword>
            </Fraud>
        </Rules>
    </Services>
    <Security>
        <PublicKey>U3RpbGxpbmdhcg==</PublicKey>
        <Factor>33543</Factor>
        <Flag>126</Flag>
        <TimeUnit>DAYS</TimeUnit>
        <LockDuration>P5Y2M10D</LockDuration>
    </Security>
    <Logging>
        <log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
            <root>
                <priority value="warn" />
            </root>
        </log4j:configuration>
    </Logging>
    <ApplicationContext>
		<beans:beans xmlns:beans="http://www.springframework.org/schema/beans"
			xmlns:context="http://www.springframework.org/schema/context" xmlns:p="http://www.springframework.org/schema/p"
			xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
				http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd">
		</beans:beans>
    </ApplicationContext>
</Configuration>
